### ISSUE TITLE
CI sometimes fails in solidity mapper tests for fixed size array

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/watcher-ts#167]
Creating an array with random bytes throws error:
```
@vulcanize/solidity-mapper:   2) Get value from storage
@vulcanize/solidity-mapper:        fixed size arrays
@vulcanize/solidity-mapper:          get value of dynamic bytes type array by index:
@vulcanize/solidity-mapper:      Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="26357769298393163104213332638035960202910785164718706254165680010689511426", code=NUMERIC_FAULT, version=bignumber/5.6.2)
@vulcanize/solidity-mapper:       at Logger.makeError (/home/runner/work/watcher-ts/watcher-ts/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
@vulcanize/solidity-mapper:       at Logger.throwError (/home/runner/work/watcher-ts/watcher-ts/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
@vulcanize/solidity-mapper:       at throwFault (/home/runner/work/watcher-ts/watcher-ts/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:356:19)
@vulcanize/solidity-mapper:       at BigNumber.toNumber (/home/runner/work/watcher-ts/watcher-ts/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:186:13)
@vulcanize/solidity-mapper:       at /home/runner/work/watcher-ts/watcher-ts/packages/solidity-mapper/src/storage.ts:361:38
@vulcanize/solidity-mapper:       at step (src/storage.ts:47:23)
@vulcanize/solidity-mapper:       at Object.next (src/storage.ts:28:53)
@vulcanize/solidity-mapper:       at fulfilled (src/storage.ts:19:58)
@vulcanize/solidity-mapper: error Command failed with exit code 2.
```

**Comment by AFDudley** [comment]
Did we ever see this in production?

**Comment by nikugogoi** [comment]
We didn't see this error in production when using storage based access.
Later we switched to eth calls in production.

The error is thrown only for bytes value of length less than 32 and with leading zeros.
Will add more tests for different bytes type values.
