### ISSUE TITLE
Test eden-watcher with mainnet data

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/watcher-ts#70]
- [x] GQL query metrics
- [x] Slow query analysis

**Comment by nikugogoi** [comment]
Error in job-runner at block 12964797 (16505 blocks from start)
```
time:indexer#createDiffStaged-auto_diff: 14.562ms
2022-08-02T19:04:55.050Z vulcanize:job-queue Error in queue event-processing job b727fea0-1262-11ed-82fb-bb9814572730
2022-08-02T19:04:55.052Z vulcanize:job-queue QueryFailedError: invalid input value for enum producer_set_change_change_type_enum: "Added"
    at QueryFailedError.TypeORMError [as constructor] (/srv/watchers/watcher-ts/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/srv/watchers/watcher-ts/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/srv/watchers/watcher-ts/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/srv/watchers/watcher-ts/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/srv/watchers/watcher-ts/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/srv/watchers/watcher-ts/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by nikugogoi** [comment]
Error in job-runner at block 12966529 (18237 blocks from start)
```bash
time:common#processBacthEvents-fetching_events_batch: 7.45ms
2022-08-06T08:00:23.266Z vulcanize:common Processing events batch from index 134 to 134
2022-08-06T08:00:23.273Z vulcanize:job-queue Error in queue event-processing job 561edf40-14ea-11ed-8c71-a1c3a76d9e12
2022-08-06T08:00:23.275Z vulcanize:job-queue TypeError: Cannot read properties of null (reading '-1')
    at BN.bitLength (/srv/watchers/watcher-ts/node_modules/bn.js/lib/bn.js:635:23)
    at BN.byteLength (/srv/watchers/watcher-ts/node_modules/bn.js/lib/bn.js:667:27)
    at /srv/watchers/watcher-ts/packages/graph-node/src/loader.ts:433:34
    at step (/srv/watchers/watcher-ts/packages/graph-node/dist/loader.js:36:23)
    at Object.next (/srv/watchers/watcher-ts/packages/graph-node/dist/loader.js:17:53)
    at /srv/watchers/watcher-ts/packages/graph-node/dist/loader.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/watchers/watcher-ts/packages/graph-node/dist/loader.js:7:12)
    at bigInt.fromString (/srv/watchers/watcher-ts/packages/graph-node/src/loader.ts:421:44)
    at /srv/watchers/watcher-ts/node_modules/asyncify-wasm/dist/asyncify.cjs:1:499
```
